# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"\x1b\n\x0bRequestAuth\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0cResponseAuth\x12\x0e\n\x06isAuth\x18\x01 \x01(\x08\x32\x32\n\x0b\x41uthService\x12#\n\x04\x41uth\x12\x0c.RequestAuth\x1a\r.ResponseAuthb\x06proto3')



_REQUESTAUTH = DESCRIPTOR.message_types_by_name['RequestAuth']
_RESPONSEAUTH = DESCRIPTOR.message_types_by_name['ResponseAuth']
RequestAuth = _reflection.GeneratedProtocolMessageType('RequestAuth', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTAUTH,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:RequestAuth)
  })
_sym_db.RegisterMessage(RequestAuth)

ResponseAuth = _reflection.GeneratedProtocolMessageType('ResponseAuth', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEAUTH,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:ResponseAuth)
  })
_sym_db.RegisterMessage(ResponseAuth)

_AUTHSERVICE = DESCRIPTOR.services_by_name['AuthService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTAUTH._serialized_start=14
  _REQUESTAUTH._serialized_end=41
  _RESPONSEAUTH._serialized_start=43
  _RESPONSEAUTH._serialized_end=73
  _AUTHSERVICE._serialized_start=75
  _AUTHSERVICE._serialized_end=125
# @@protoc_insertion_point(module_scope)
